"""HRRR-VLM: Visual-Language Model for High-Resolution Rapid Refresh (HRRR) data
from the National Oceanic and Atmospheric Administration (NOAA).
"""

from .data import (
    DEFAULT_VARIABLES,
    LATITUDE_MAX,
    LATITUDE_MIN,
    LONGITUDE_MAX,
    LONGITUDE_MIN,
    MODEL_CONFIGS,
    REGION_MODEL_PAIRS,
    REGIONS,
    WEATHER_VARIABLES,
    CaptionGenerator,
    CaptionMetadata,
    ConfigurationError,
    DataGeneratorConfig,
    DataLoadError,
    HRRRImageCaptionDataset,
    HRRRVLMError,
    ModelConfig,
    RegionConfig,
    TrainingRecord,
    ValidationError,
    WeatherDataError,
    WeatherDataGenerator,
    WeatherDataService,
    WeatherStatistics,
    WeatherVariableConfig,
    get_first_mondays,
)
from .eval import (
    PREDICTION_THRESHOLD,
    ClusteringResults,
    DendrogramGenerator,
    EmbeddingClusterer,
    EmbeddingData,
    EmbeddingExtractor,
    HurricaneDataProcessor,
    HurricanePredictionResults,
    HurricanePredictor,
    RetrievalEvaluationError,
    RetrievalEvaluator,
    filter_embeddings_by_date,
    run_linear_probe_analysis,
)
from .train import (
    DataError,
    HRRRImageCaptionDataSetup,
    HRRRLoRASigLIPTrainer,
    ModelInitError,
    ModelTrainingConfig,
    ModelTrainingError,
    training_init,
)
from .utils import configure_logger

__version__ = "0.1.0"
__author__ = "Adam Muhtar"

__all__ = [
    "DEFAULT_VARIABLES",
    "LATITUDE_MAX",
    "LATITUDE_MIN",
    "LONGITUDE_MAX",
    "LONGITUDE_MIN",
    "MODEL_CONFIGS",
    "PREDICTION_THRESHOLD",
    "REGIONS",
    "REGION_MODEL_PAIRS",
    "WEATHER_VARIABLES",
    "CaptionGenerator",
    "CaptionMetadata",
    "ClusteringResults",
    "ConfigurationError",
    "DataError",
    "DataGeneratorConfig",
    "DataLoadError",
    "DendrogramGenerator",
    "EmbeddingClusterer",
    "EmbeddingData",
    "EmbeddingExtractor",
    "HRRRImageCaptionDataSetup",
    "HRRRImageCaptionDataset",
    "HRRRLoRASigLIPTrainer",
    "HRRRVLMError",
    "HurricaneDataProcessor",
    "HurricanePredictionResults",
    "HurricanePredictor",
    "ModelConfig",
    "ModelInitError",
    "ModelTrainingConfig",
    "ModelTrainingError",
    "RegionConfig",
    "RetrievalEvaluationError",
    "RetrievalEvaluator",
    "TrainingRecord",
    "ValidationError",
    "WeatherDataError",
    "WeatherDataGenerator",
    "WeatherDataService",
    "WeatherStatistics",
    "WeatherVariableConfig",
    "configure_logger",
    "filter_embeddings_by_date",
    "get_first_mondays",
    "run_linear_probe_analysis",
    "training_init",
]
