[tox]
envlist = py311,py312,py313,py314,lint,type-check

[pytest]
testpaths = tests
python_classes = Test*
python_files = test_*.py
python_functions = test_*
addopts =
    --strict-config
    --strict-markers
    --verbose
filterwarnings =
    ignore::DeprecationWarning:herbie.core
    ignore::PendingDeprecationWarning:herbie.paint
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning

[testenv]
runner = uv-venv-lock-runner
skip-install = true
dependency_groups = test
commands =
    pytest tests/ --cov --cov-report xml:coverage.xml --junitxml junit-pytest.xml

[testenv:lint]
runner = uv-venv-lock-runner
skip-install = true
dependency_groups = lint
commands = 
    ruff check

[testenv:type-check]
runner = uv-venv-lock-runner
skip-install = true
dependency_groups = dev
commands = 
    ty check src